@Host = http://localhost:8088
@Auth = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE3NjExNjQ2MzcsImlhdCI6MTc2MTE2NDYzNywiZXhwIjoxNzYxMTY0OTM3LCJ0aXBvIjoiTm9ybWFsIiwiaWQiOiIxdmwwbXZ0emFmZWtxMjM1cDJ0eSJ9.Fo3cJnzEd-U--wKOgLWbdT_Ac42fO4J5Kt3OpPifxa0
@Id = s7wqlxg8tv2eneopto42

#REGISTER
GET {{Host}}/register
Content-Type: application/json

###
#LOGIN
POST {{Host}}/login
Content-Type: application/json

{
  "device": "1vl0mvtzafekq235p2ty"
}

###
#Get all days
GET {{Host}}/days/
Content-Type: application/json
Authorization: Bearer {{Auth}}

###
#Get all exercises
GET {{Host}}/exercises/
Content-Type: application/json
Authorization: Bearer {{Auth}}


###
#Post day
POST {{Host}}/days/
Content-Type: application/json
Authorization: Bearer {{Auth}}

{
  "id": null,
  "state": "Free",
  "date": "2025-10-22",
  "exercises": []
}

###
#Update Exercises
PUT {{Host}}/days/{{Id}}
Content-Type: application/json
Authorization: Bearer {{Auth}}

[]


###
#Save a book
POST {{Host}}/api/v1/books/
Content-Type: application/json
Authorization: Bearer {{Auth}}

{
  "titulo": "Dios es el evangelio",
  "autor": "John Piper",
  "isbn": "978-0-8254-5712-8",
  "editorial": "Editorial Portavoz",
  "pub_year": 2005,
  "edicion": 2007,
  "paginas": 153,
  "prestamo": "None"
}

###
#Get all exercises
GET {{Host}}/exercises/
Content-Type: application/json
Authorization: Bearer {{Auth}}

###
#Get all routines
GET {{Host}}/routines/
Content-Type: application/json
Authorization: Bearer {{Auth}}

###
#Save new Routine
POST {{Host}}/routines/
Content-Type: application/json
Authorization: Bearer {{Auth}}

{
  "templates": [
    [
      {
        "group": "Biceps",
        "id": "s7wqlxg8tv2eneopto42",
        "name": "Curl",
        "series": [
          {
            "count": 1,
            "weight": 1.4
          },
          null,
          null,
          null
        ]
      }
    ]
  ],
  "created_by": "Lucas"
}