#@Host = https://renuevobackendqa.onrender.com
@Host = http://localhost:8088
@Auth = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE3NjEyNDkxMTYsImlhdCI6MTc2MTI0OTExNiwiZXhwIjoxNzYxMjQ5NDE2LCJ0aXBvIjoiTm9ybWFsIiwiaWQiOiJsMmNoYzkwa3Z6NTlnbWZ1ZW5xNiJ9.CSK4UGF6ev5qfKMdKZMvaTEdxc4qbfRWcxilG_VKjTo
@Id = s7wqlxg8tv2eneopto42


#REGISTER
GET {{Host}}/register
Content-Type: application/json

###
#LOGIN
POST {{Host}}/login
Content-Type: application/json

{
  "device": "l2chc90kvz59gmfuenq6"
}